### ISSUE TITLE
On enable error

### ISSUE THREAD

**Issue by DrexPlayz** [heirteir/AutoEye#31]
## Error description

**What happend?:**
I was turning on my server when out of nowhere I get this error which causes me a lot of problems when it comes to detecting hacks
**What should happen?:**
The plugin should start without any problem
**Video** (_not needed but very helpful_):
I do not have video about the error
## Useful information
This error happens in the latest version of your plugin
**Plugin Version:**
0.67C
**Server Version:**
PaperSpigot 1.7-1.8
**Minecraft Version:**
1.7-1.8
**Other Plugins:**
Use plugins for UHC, Skript, etc.
**Does the Server use ViaVersion?:**
Nope
**Console output** (_If the plugin throw an error in the console post the log here. Please use a [gist](https://gist.github.com/) or [hastebin](https://hastebin.com)_):
https://gist.github.com/DrexPlayz/e328ff6e63fb52fdd6bd1ad622eaa8e9

**Comment by kenbear101** [comment]
According to the console errors it looks like a version error. This could be because of your PaperSpigot 
version. Try using viaversion if that does not solve the issue I would recommend using regular spigot. There is not a real big difference. 

`[17:19:48 ERROR]: Error occurred while enabling Autoeye v0.67C (Is it up to date?) 
java.lang.NullPointerException `

**Comment by kenbear101** [comment]
Also, have you tried using other AutoEye versions?

**Comment by heirteir** [comment]
I noticed this error myself when testing. It will be fixed in the next version I upload to Spigot. Thank you for reporting it.
